-- Flyway V1 baseline schema for Meer
-- Generated from meer_dev (Postgres 15, PostGIS). Applies core schema and extensions.

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;
CREATE SCHEMA IF NOT EXISTS topology;
CREATE EXTENSION IF NOT EXISTS postgis_topology WITH SCHEMA topology;

-- Users
CREATE TABLE public.auth_user (
    notify_new_stores boolean NOT NULL,
    notify_promos boolean NOT NULL,
    created_at timestamp(6) with time zone,
    id uuid NOT NULL,
    owned_thrift_store_id uuid,
    bio character varying(1000),
    display_name character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    photo_url character varying(255),
    role character varying(255) NOT NULL,
    CONSTRAINT auth_user_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);

CREATE TABLE public.auth_user_favorites (
    auth_user_id uuid NOT NULL,
    thrift_store_id uuid NOT NULL
);

-- Catalog
CREATE TABLE public.category (
    id character varying(64) NOT NULL,
    image_res_id character varying(255) NOT NULL,
    name_string_id character varying(255) NOT NULL
);

-- Content
CREATE TABLE public.guide_content (
    id integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    thrift_store_id uuid,
    image_url character varying(512) NOT NULL,
    description character varying(2048) NOT NULL,
    category_label character varying(255) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL
);

ALTER TABLE public.guide_content ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.guide_content_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Feedback
CREATE TABLE public.store_feedback (
    id integer NOT NULL,
    score integer,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    auth_user_id uuid NOT NULL,
    thrift_store_id uuid NOT NULL,
    body text
);

ALTER TABLE public.store_feedback ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.store_feedback_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Support
CREATE TABLE public.support_contact (
    id integer NOT NULL,
    created_at timestamp(6) with time zone NOT NULL,
    email character varying(255) NOT NULL,
    message text NOT NULL,
    name character varying(255) NOT NULL
);

ALTER TABLE public.support_contact ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.support_contact_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Stores
CREATE TABLE public.thrift_store (
    latitude double precision,
    longitude double precision,
    created_at timestamp(6) with time zone NOT NULL,
    updated_at timestamp(6) with time zone NOT NULL,
    id uuid NOT NULL,
    owner_id uuid,
    description character varying(1000),
    cover_image_url character varying(2048),
    facebook character varying(2048),
    instagram character varying(2048),
    tagline character varying(2048),
    website character varying(2048),
    address_line character varying(255) NOT NULL,
    badge_label character varying(255),
    email character varying(255),
    name character varying(255) NOT NULL,
    neighborhood character varying(255),
    opening_hours character varying(255),
    phone character varying(255)
);

CREATE TABLE public.thrift_store_categories (
    thrift_store_id uuid NOT NULL,
    categories character varying(255)
);

CREATE TABLE public.thrift_store_gallery_urls (
    thrift_store_id uuid NOT NULL,
    gallery_urls character varying(2048)
);

CREATE TABLE public.thrift_store_photo (
    display_order integer NOT NULL,
    id integer NOT NULL,
    thrift_store_id uuid NOT NULL,
    url character varying(255) NOT NULL
);

ALTER TABLE public.thrift_store_photo ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.thrift_store_photo_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

-- Constraints
ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_email_key UNIQUE (email);

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_owned_thrift_store_id_key UNIQUE (owned_thrift_store_id);

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.auth_user_favorites
    ADD CONSTRAINT auth_user_favorites_pkey PRIMARY KEY (auth_user_id, thrift_store_id);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_name_string_id_key UNIQUE (name_string_id);

ALTER TABLE ONLY public.category
    ADD CONSTRAINT category_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.guide_content
    ADD CONSTRAINT guide_content_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.store_feedback
    ADD CONSTRAINT store_feedback_auth_user_id_thrift_store_id_key UNIQUE (auth_user_id, thrift_store_id);

ALTER TABLE ONLY public.store_feedback
    ADD CONSTRAINT store_feedback_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.support_contact
    ADD CONSTRAINT support_contact_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.thrift_store
    ADD CONSTRAINT thrift_store_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.thrift_store_photo
    ADD CONSTRAINT thrift_store_photo_pkey PRIMARY KEY (id);

-- Foreign keys
ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT fk4boaylqi7gt9p1ljtyv6irkmg FOREIGN KEY (owned_thrift_store_id) REFERENCES public.thrift_store(id);

ALTER TABLE ONLY public.auth_user_favorites
    ADD CONSTRAINT fk3bfnsb3r1q5c0hw4gm2xito35 FOREIGN KEY (auth_user_id) REFERENCES public.auth_user(id);

ALTER TABLE ONLY public.auth_user_favorites
    ADD CONSTRAINT fk95c6myn0c5ta7rwgmg5pm5xwn FOREIGN KEY (thrift_store_id) REFERENCES public.thrift_store(id);

ALTER TABLE ONLY public.guide_content
    ADD CONSTRAINT fk3lv4id3m515hmtf91a0iid606 FOREIGN KEY (thrift_store_id) REFERENCES public.thrift_store(id);

ALTER TABLE ONLY public.store_feedback
    ADD CONSTRAINT fk7jwlqr4ap7i0pfve5tltga5ut FOREIGN KEY (auth_user_id) REFERENCES public.auth_user(id);

ALTER TABLE ONLY public.store_feedback
    ADD CONSTRAINT fkg1m61mcatsh8cnyeyrem7hd72 FOREIGN KEY (thrift_store_id) REFERENCES public.thrift_store(id);

ALTER TABLE ONLY public.thrift_store
    ADD CONSTRAINT fktp9qnt9ulvo8yimy43y4bnf6e FOREIGN KEY (owner_id) REFERENCES public.auth_user(id);

ALTER TABLE ONLY public.thrift_store_categories
    ADD CONSTRAINT fk6afss8a46orndprn0q6bx9y5b FOREIGN KEY (thrift_store_id) REFERENCES public.thrift_store(id);

ALTER TABLE ONLY public.thrift_store_gallery_urls
    ADD CONSTRAINT fkmxsp16i5k4ppb9vy8vmuei95f FOREIGN KEY (thrift_store_id) REFERENCES public.thrift_store(id);

ALTER TABLE ONLY public.thrift_store_photo
    ADD CONSTRAINT fk1l96gkou14ekl1wuay07rjto5 FOREIGN KEY (thrift_store_id) REFERENCES public.thrift_store(id);
