create table if not exists support_contact (
    id integer generated by default as identity primary key,
    name varchar(255) not null,
    email varchar(255) not null,
    message text not null,
    created_at timestamp not null default current_timestamp
);
